# src/interfaces/ui_interfaces.py
from typing import Protocol, Optional, runtime_checkable
from ..models.update import UpdateInfo

@runtime_checkable
class UIManager(Protocol):
    """Interface para gerenciamento geral de UI"""
    def show_update_available_dialog(self, update_info: UpdateInfo) -> None: ...
    def show_download_progress_window(self, download_url: str, version: str, app_exec: str) -> None: ...
    def show_error_dialog(self, title: str, message: str) -> None: ...
    def show_info_dialog(self, title: str, message: str) -> None: ...
    def show_confirm_dialog(self, title: str, message: str) -> bool: ...